run:
  go: "1.26"
  timeout: 5m

linters:
  enable:
    - gosec
    - staticcheck
    - errcheck
    - bodyclose
    - noctx
    - exhaustive
    - nilerr
    - contextcheck
    - gocritic

linters-settings:
  gosec:
    severity: medium
    confidence: medium
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: "_test.go"
      linters:
        - errcheck
