run:
  go: "1.26"
  timeout: 5m

linters:
  enable:
    - gosec
    - staticcheck
    - errcheck
    - bodyclose
    - noctx
    - contextcheck
    - gocritic
    - revive

linters-settings:
  gosec:
    excludes:
      - G104 # redundant with errcheck
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: "_test.go"
      linters:
        - errcheck
